version: "3.9"
services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
    - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: admin_db
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  nest-app:
    build: .
    container_name: nest-app
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - "${NEST_PORT}:3000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  pgdata: